config/routes.rb
Rails.application.routes.draw do
  root 'sources#index'
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  
  resources :sources, except: %i[show] do
    resources :source_pages
  end

  resources :products, except: %i[new create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :source_page, required: false
  belongs_to :source

  validates :url, presence: true, uniqueness: true
  # validates :price, numericality: { greater_than: 0 }, on: :update

  after_update :format_price

  def format_price
    price = self.price.to_f
    "#{format('%.3f', price).gsub('.', ',')} EGP"
  end

  def product_image
    image_url = self.image_url.split(',')
    image_url.first
  end

  def enqueue_scraper_job
    ProductDetailsJob.perform_async(id)
  end
end

app/models/source.rb
class Source < ApplicationRecord
  URL_REGEXP = Regexp.new("(https:\/\/www\.|http:\/\/www\.|https:\/\/|http:\/\/)?[a-zA-Z0-9]{2,}\.[a-zA-Z0-9]{2,}\.[a-zA-Z0-9]{2,}(\.[a-zA-Z0-9]{2,})?")
 
  validates :name, presence: true
  validates :url, presence: true, uniqueness: true, format: { with: URL_REGEXP }

  has_many :source_pages, dependent: :destroy
  has_many :products, dependent: :destroy

  has_one :source_config
  accepts_nested_attributes_for :source_config, allow_destroy: true, update_only: true
end

app/models/source_config.rb
class SourceConfig < ApplicationRecord
    belongs_to :source
end

app/models/source_page.rb
class SourcePage < ApplicationRecord
  URL_REGEXP = Regexp.new("(https:\/\/www\.|http:\/\/www\.|https:\/\/|http:\/\/)?[a-zA-Z0-9]{2,}\.[a-zA-Z0-9]{2,}\.[a-zA-Z0-9]{2,}(\.[a-zA-Z0-9]{2,})?")

  validates :name, presence: true
  validates :url, presence: true, uniqueness: true, format: { with: URL_REGEXP }

  delegate :source_config, to: :source

  belongs_to :source
  has_many :products
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  CACHE_KEY = 'products#index'
  before_action :set_product, only: %i[show edit update destroy]

  before_action :check_cached, only: :index
  after_action :cache_response, only: :index

  # GET /products or /products.json
  def index
    if @cache_response
      render html: @cached_response.html_safe
    else
      @products = Product.all.order('RANDOM()')
    end
  end

  # GET /products/1 or /products/1.json
  def show; end

  # GET /products/1/edit
  def edit; end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def product_params
    params.require(:product).permit(:name, :price, :url, :image_url, :description, :source_page_id)
  end

  def check_cached
    @cached_response = REDIS_CLIENT.get(CACHE_KEY)
  end

  def cache_response
    REDIS_CLIENT.setex(CACHE_KEY, 3.houres, response.body)
  end
end

app/controllers/source_pages_controller.rb
class SourcePagesController < ApplicationController
  before_action :set_source, only: %i[index new create edit update destroy]
  before_action :set_source_page, only: %i[edit update destroy]

  # GET /source_pages or /source_pages.json
  def index
    @source_pages = @source.source_pages.all
  end

  # GET /source_pages/1 or /source_pages/1.json
  def show
  end

  # GET /source_pages/new
  def new
    @source_page = SourcePage.new
  end

  # GET /source_pages/1/edit
  def edit
  end

  # POST /source_pages or /source_pages.json
  def create
    @source_page = @source.source_pages.create(source_page_params)

    respond_to do |format|
      if @source_page.save
        format.html { redirect_to source_source_pages_path, notice: "Source page was successfully created." }
        format.json { render :show, status: :created, location: @source_page }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @source_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /source_pages/1 or /source_pages/1.json
  def update
    respond_to do |format|
      if @source_page.update(source_page_params)
        format.html { redirect_to source_source_pages_path, notice: "Source page was successfully updated." }
        format.json { render :show, status: :ok, location: @source_page }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @source_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /source_pages/1 or /source_pages/1.json
  def destroy
    @source_page.destroy

    respond_to do |format|
      format.html { redirect_to source_source_pages_path, notice: "Source page was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_source
      @source = Source.find(params[:source_id])
    end
  
    def set_source_page
      @source_page = SourcePage.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def source_page_params
      params.require(:source_page).permit(:name, :url, :source_id)
    end
end

app/controllers/sources_controller.rb
class SourcesController < ApplicationController
  before_action :set_source, only: %i[ edit update destroy ]

  # GET /sources or /sources.json
  def index
    @sources = Source.all
  end

  # GET /sources/new
  def new
    @source = Source.new
    @source.build_source_config
  end

  # GET /sources/1/edit
  def edit
  end

  # POST /sources or /sources.json
  def create
    @source = Source.new(source_params)

    respond_to do |format|
      if @source.save
        format.html { redirect_to sources_path, notice: "Source was successfully created." }
        format.json { render :index, status: :created, location: @source }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @source.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sources/1 or /sources/1.json
  def update
    respond_to do |format|
      if @source.update(source_params)
        format.html { redirect_to sources_path, notice: "Source was successfully updated." }
        format.json { render :index, status: :ok, location: @source }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @source.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sources/1 or /sources/1.json
  def destroy
    @source.destroy

    respond_to do |format|
      format.html { redirect_to sources_url, notice: "Source was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_source
      @source = Source.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def source_params
      params.require(:source).permit(:name, :url, source_config_attributes:
        %i[name_selector image_url_selector description_selector products_url_selector])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/source_pages_helper.rb
module SourcePagesHelper
end

app/helpers/sources_helper.rb
module SourcesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sa3dawy</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@3.9.1/dist/chart.min.js"></script>

    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>

    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

  </head>

  <body style="margin: 10px; background-color: #202429;">
    <%= yield %>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block", class: "text-light" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :price, style: "display: block", class: "text-light" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :url, style: "display: block", class: "text-light" %>
    <%= form.text_field :url %>
  </div>

  <div>
    <%= form.label :image_url, style: "display: block", class: "text-light" %>
    <%= form.text_field :image_url %>
  </div>

  <div>
    <%= form.label :description, style: "display: block", class: "text-light" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :source_page_id, style: "display: block", class: "text-light" %>
    <%= form.text_field :source_page_id %>
  </div>

  <br>
  <div>
    <%= form.submit class: "btn btn-success col-2" %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div class="text-center">
  <h1 class="text-light"><%= @product.name %></h1>
  <p class="text-light col-2 mx-auto">
    <%= @product.description %>
  </p>
  <p class="text-light"><strong>Price:</strong><span class="text-primary"><%= " #{@product.price} EGP" %></span></p>

  <% unless @product.image_url.nil? %>
    <% image_urls = @product.image_url.split(',') %>
    <% image_urls.each_slice(3) do |image_slice| %>
      <div class="row d-flex justify-content-center">
        <% image_slice.each do |image_url| %>
          <div>
            <%= image_tag(image_url.strip, class: "img-fluid rounded", style: "width: 300px; height: 300px; object-fit: cover; margin: 4px;", loading: "lazy") %>
          </div>
        <% end %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/products/_table.html.erb
<table class="table table-bordered table-dark">
  <thead>
  <tr>
    <th scope="col">#</th>
    <th scope="col">Name</th>
    <th scope="col">Url</th>
    <th scope="col">Price</th>
    <th scope="col">Description</th>
    <th scope="col">Image</th>
    <th scope="col">Actions</th>
  </tr>
  </thead>
  <tbody>
  <% @products.each do |product| %>
    <tr>
      <th class="col-1"><%= product.id %></th>
      <th class="col-2"><%= product.name %></th>
      <td class="col-1"><%= link_to "Product page", product.url %></td>
      <td class="col-1"><%="#{product.price} EGP"%></td>
      <td class="col-2">
        <details>
          <summary style="background-color: #202429; border-radius: 6px; padding: 6px;">Full description</summary>
          <br>
          <p><%= product.description %></p>
        </details>
      </td>
      <td class="col-1">
        <% unless product.image_url.nil? %>
          <% image_urls = product.image_url.split(',') %>
          <% first_image_url = image_urls.first.strip %>
          <%= image_tag(first_image_url, :size => '300x300', class: "rounded", style: " object-fit: cover;", loading: "lazy") %>
        <% end %>
      </td>
       <td class="col-1">
          <div class="btn-group">
            <a href=<%= edit_product_path(product) %> style="text-decoration:none; margin: 1px 10px 1px 10px;">
              <input class="btn btn-outline-success" type="button" value="Edit">
            </a>

            <a href=<%= product_path(product) %> style="text-decoration:none;">
              <input class="btn btn-outline-primary" type="button" value="Show">
            </a>

          </div>
      </td>
    </tr>
  <% end %>
</table>

app/views/products/edit.html.erb
<h1 class="text-light">Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product, class: "btn btn-outline-primary" %> |
  <%= link_to "Back to products", products_path, class: "btn btn-outline-light" %>
</div>

app/views/products/index.html.erb
<div>
  <h1 class="text-light">Products <%= @products.count%></h1>

  <%= render 'table' %>
</div>

app/views/products/show.html.erb
<%= render 'product' %>
<br>
<div class="text-center">

    <%= link_to 'Edit this product', edit_product_path(@product), class: 'btn btn-outline-success' %>
    <%= link_to 'Back to products', products_path, class: 'btn btn-outline-primary' %>
    <%= button_to "Delete this product", @product, method: :delete, class: 'btn btn-outline-danger col-2', style: "margin: 10px;" %>
</div>

app/views/source_pages/_form.html.erb
<div>
  <%= form_with model: [ @source, @source_page ] do |form| %>
  <p class="col-3">
    <%= form.label :name, class: "text-light" %><br>
    <%= form.text_field :name, class: "form-control" %>
    <% @source_page.errors.full_messages_for(:name).each do |message| %>
        <div class="text-danger"><%= message %></div>
    <% end %>
  </p>
  <p class="col-4">
    <%= form.label :url, class: "text-light" %><br>
    <%= form.text_area :url, class: "form-control" %>
    <% @source_page.errors.full_messages_for(:url).each do |message| %>
        <div class="text-danger"><%= message %></div>
    <% end %>
  </p>
  <p>
    <button type="submit" class="btn btn-success col-4" style="margin: 14px;">Submit</button>
  </p>
<% end %>
</div>

app/views/source_pages/_table.html.erb
<table class="table table-bordered table-dark">
  <thead>
  <tr>
    <th scope="col">#</th>
    <th scope="col">Name</th>
    <th scope="col">Url</th>
    <th scope="col">Products Count</th>
    <th scope="col">Actions</th>
  </tr>
  </thead>
  <tbody>
  <% @source_pages.each do |source_page| %>
    <tr>
      <th><%= source_page.id %></th>
      <td><%= source_page.name %></td>
      <td><%= link_to source_page.url, source_page.url %></td>
      <td><%= source_page.products.count %></td>
      <td>
        <div class="btn-group">
            <a href=<%= edit_source_source_page_path(@source, source_page) %> style="text-decoration:none; margin: 1px 10px 1px 10px;">
              <input class="btn btn-outline-success" type="button" value="Edit">
            </a>
            <%= button_to 'Delete', source_source_page_path(@source, source_page), class: 'btn btn-outline-danger', style: "margin: 1px 10px 1px 10px;" ,method: :delete %>
        </div>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/source_pages/edit.html.erb
<div>
  <h2 class="text-light col-12">Edit Source Page <%= @source_page.name %> </h2>

  <%= render partial: "form", source: @source_page %>
</div>

app/views/source_pages/index.html.erb
<h1 class="text-light">Source Pages <%= link_to "Add Page", new_source_source_page_path, class: 'btn btn-outline-success' %></h1>
<%= render partial: "table" %>

app/views/source_pages/new.html.erb
<div>
  <h2 class="text-light col-12">New Source Page for <%= @source.name %> </h2>

  <%= render partial: "form", source: @source_page %>
</div>

app/views/sources/_form.html.erb
<%= form_with model: @source do |form| %>
  <div>
    <%= form.label :name, class: "text-light" %><br>
      <%= form.text_field :name %>
        <% @source.errors.full_messages_for(:name).each do |message| %>
          <div class="text-danger">
            <%= message %>
          </div>
          <% end %>
  </div>

  <br>
  <div>
    <%= form.label :url, class: "text-light" %><br>
      <%= form.text_field :url %>
        <% @source.errors.full_messages_for(:url).each do |message| %>
          <div class="text-danger">
            <%= message %>
          </div>
          <% end %>
  </div>

  <br>
  <div style="margin-top: 20px;">
    <h2 class="text-light">Source Config</h2>
  </div>

  <div>
    <%= form.fields_for :source_config do |source_config| %>
      <div>
        <%= source_config.label :name_selector, class: "text-light" %><br>
        <%= source_config.text_field :name_selector %>
      </div>
      <div>
        <%= source_config.label :description_selector, class: "text-light" %><br>
        <%= source_config.text_field :description_selector %>
      </div>
      <div>
        <%= source_config.label :image_url_selector, class: "text-light" %><br>
        <%= source_config.text_field :image_url_selector %>
      </div>
      <div>
        <%= source_config.label :products_url_selector, class: "text-light" %><br>
        <%= source_config.text_field :products_url_selector %>
      </div>
      <% end %>
  </div>

  <button type="submit" class="btn btn-success" style="margin-top: 20px;">Submit</button>

  <% end %>

app/views/sources/_table.html.erb
<table class="table table-bordered table-dark">
  <thead>
  <tr>
    <th scope="col">#</th>
    <th scope="col">Name</th>
    <th scope="col">Url</th>
    <th scope="col">Products Count</th>
    <th scope="col">Actions</th>
  </tr>
  </thead>
  <tbody class="table-dark">
  <% @sources.each do |source| %>
    <tr>
      <th><%= source.id %></th>
      <td><%= source.name %></td>
      <td><%= link_to source.url, source.url %></td>
      <td><%= source.products.count %></td>
      <td>
        <div class="btn-group">
          <%= link_to "Edit Source", edit_source_path(source), class: 'btn btn-outline-success btn-sm', style: "margin: 1px 10px 1px 10px;" %>
          <%= link_to "Add Source Page", new_source_source_page_path(source), class: 'btn btn-outline-success btn-sm', style: "margin: 1px 10px 1px 10px;" %>
          <%= link_to "Show Source Pages", source_source_pages_path(source), class: 'btn btn-outline-light btn-sm',style: "margin: 1px 1px 1px 1px;" %>
        </div>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/sources/edit.html.erb
<div>
  <h1 class="text-light">Edit Source</h1>

  <%= render partial: "form", source: @source %>
</div>

app/views/sources/index.html.erb
<h1 class="text-light">
    Sources 
    <%= link_to "New Source", new_source_path, class: 'btn btn-outline-success' %> 
    <%= link_to "Products", products_path, class: 'btn btn-primary' %> 
</h1>

<%= render partial: "table" %>

app/views/sources/new.html.erb
<div>
  <h2 class="text-light">New Source</h2>
  <%= render partial: "form", source: @source %>
</div>